# Paid Plan Endpoints

In [1]:
import sys
sys.path.append('..')  # This adds the parent directory to the Python path

In [2]:
import keyring
from pycgapi import CoinGeckoAPI

In [3]:
api_key = keyring.get_password('coingecko', 'analyst_api_key')

In [4]:
api = CoinGeckoAPI(api_key, pro_api=True)
status = api.status_check()
print("API Server Status:", status)

API Server Status: {'gecko_says': '(V3) To the Moon!'}

## /coins/list/new

In [5]:
latest_coins_listed = api.new_coins_listed()
latest_coins_listed.head()

                  id symbol               name  activated_at
0             zkfair    zkf             ZKFair    1704455149
1           coingrab   grab           CoinGrab    1704453894
2            party-2  party              Party    1704453751
3              opsec  opsec              OpSec    1704453269
4  terahertz-capital    thz  TeraHertz Capital    1704453176

## /coins/top_gainers_losers

In [6]:
gainers, losers = api.gainers_losers()

In [7]:
gainers.head()

,id,symbol,name,image,market_cap_rank,usd,usd_24h_vol,usd_24h_change
0,zmine,zmn,ZMINE,https://assets.coingecko.com/coins/images/2103...,536,0.090033,9.131399e+04,405.547998
1,shido-2,shido,Shido,https://assets.coingecko.com/coins/images/3207...,550,0.005570,1.034826e+07,123.969528
2,uquid-coin,uqc,Uquid Coin,https://assets.coingecko.com/coins/images/1341...,297,13.016297,2.213543e+06,113.599825
3,constitutiondao,people,ConstitutionDAO,https://assets.coingecko.com/coins/images/2061...,235,0.037598,9.419872e+08,45.859422
4,myro,$myro,Myro,https://assets.coingecko.com/coins/images/3287...,423,0.081831,4.225495e+07,45.528619

In [8]:
losers.head()

,id,symbol,name,image,market_cap_rank,usd,usd_24h_vol,usd_24h_change
0,everdome,dome,Everdome,https://assets.coingecko.com/coins/images/2326...,556,0.000569,3.495878e+06,-31.455452
1,crypto-asset-governance-alliance,caga,Crypto Asset Governance Alliance,https://assets.coingecko.com/coins/images/3284...,532,0.000937,1.060468e+07,-29.861394
2,dogwifcoin,wif,dogwifhat,https://assets.coingecko.com/coins/images/3356...,390,0.089505,1.316596e+07,-21.516167
3,kira-network,kex,KIRA Network,https://assets.coingecko.com/coins/images/1323...,649,0.172959,1.306279e+06,-20.029579
4,cudos,cudos,Cudos,https://assets.coingecko.com/coins/images/1365...,436,0.011773,1.168275e+06,-18.338474

## /global/market_cap_chart

In [9]:
market_cap_df, volume_df = api.historical_global_market_cap()

In [10]:
market_cap_df

              market_cap
timestamp
2013-04-29  1.661442e+09
2013-04-30  1.592765e+09
2013-05-01  1.378705e+09
2013-05-02  1.220763e+09
2013-05-03  1.075224e+09
...                  ...
2024-01-02  1.805077e+12
2024-01-03  1.713247e+12
2024-01-04  1.766189e+12
2024-01-05  1.741070e+12
2024-01-06  1.722758e+12

[3885 rows x 1 columns]

In [11]:
volume_df

                  volume
timestamp
2013-04-29  0.000000e+00
2013-04-30  0.000000e+00
2013-05-01  0.000000e+00
2013-05-02  0.000000e+00
2013-05-03  0.000000e+00
...                  ...
2024-01-02  1.070238e+11
2024-01-03  1.544155e+11
2024-01-04  9.965359e+10
2024-01-05  9.900400e+10
2024-01-06  8.637699e+10

[3885 rows x 1 columns]

## /nfts/markets

In [12]:
get_nft_markets = api.nft_market_data()
get_nft_markets.head()

,id,contract_address,asset_platform_id,name,symbol,image,description,native_currency,native_currency_symbol,floor_price,...,market_cap_24h_percentage_change,volume_24h_percentage_change,number_of_unique_addresses,number_of_unique_addresses_24h_percentage_change,volume_in_usd_24h_percentage_change,total_supply,one_day_sales,one_day_sales_24h_percentage_change,one_day_average_sale_price,one_day_average_sale_price_24h_percentage_change
0,galxe-oat-v2,0x5d666f215a85b87cb042d59662a7ecd2c8cc44e6,polygon-pos,Galaxy OAT,OAT,{'small': 'https://assets.coingecko.com/nft_co...,Galxe OAT (On-chain Achievement Token) is a di...,ethereum,ETH,"{'native_currency': 0.451132, 'usd': 1005.55}",...,"{'usd': 4.592823671974402, 'native_currency': ...","{'usd': -14.877733078423297, 'native_currency'...",2171890.0,0.06224,-14.87773,23228603.0,207.0,39.864865,0.000036,-53.604097
1,cryptopunks,0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB,ethereum,CryptoPunks,PUNK,{'small': 'https://assets.coingecko.com/nft_co...,"<h3 dir=""ltr"">What Is the CryptoPunks NFT Coll...",ethereum,ETH,"{'native_currency': 55.69, 'usd': 124159}",...,"{'usd': -1.783952860842624, 'native_currency':...","{'usd': -39.36519601683362, 'native_currency':...",NaN,0.00000,-39.36520,9994.0,2.0,-33.333333,58.495000,-7.395778
2,cometh-spaceships,0xbcd4f1ecff4318e7a0c791c7728f3830db506c71,ethereum,Cometh Spaceships,SPACESHIP,{'small': 'https://assets.coingecko.com/nft_co...,Cometh is a DeFi powered game with yield gener...,ethereum,ETH,"{'native_currency': 35.0, 'usd': 77716}",...,"{'usd': 272751.70074042893, 'native_currency':...","{'usd': 0, 'native_currency': 0}",962.0,-0.10384,0.00000,12268.0,0.0,0.000000,0.000000,0.000000
3,bored-ape-yacht-club,0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d,ethereum,Bored Ape Yacht Club,BAYC,{'small': 'https://assets.coingecko.com/nft_co...,<h3>What Is the Bored Ape Yacht Club NFT Colle...,ethereum,ETH,"{'native_currency': 26.27, 'usd': 58584}",...,"{'usd': -3.4152630667454273, 'native_currency'...","{'usd': 119.67509716719597, 'native_currency':...",5588.0,0.12543,119.67510,9998.0,51.0,131.818182,26.144704,-5.302132
4,yuliorigingenone,0x735c4a681f1649f5eee8aac871aa1d89ff056217,binance-smart-chain,YuliOriginGenOne,YOG1,{'small': 'https://assets.coingecko.com/nft_co...,Yuliverse is the World’s very First Parallel R...,binancecoin,BNB,"{'native_currency': 360.0, 'usd': 108501}",...,"{'usd': -4.525582963647497, 'native_currency':...","{'usd': 154.00704929011354, 'native_currency':...",2617.0,-0.11459,154.00705,5195.0,24.0,26.315789,0.129980,119.348441

## /nfts/{id}/market_chart

In [13]:
nft_historical_data = api.nft_historical_data(nft_id='bored-ape-yacht-club')
nft_historical_data

,floor_price_usd,floor_price_native,h24_volume_usd,h24_volume_native,market_cap_usd,market_cap_native
timestamp,,,,,,
2021-04-30 00:00:00,441.528169,0.160119,4.415282e+02,0.160119,NaN,0.0000
2021-05-01 00:00:00,194.369260,0.070000,1.275688e+05,45.942545,NaN,0.0000
2021-05-02 00:00:00,494.914781,0.168057,2.348953e+05,79.762959,NaN,0.0000
2021-05-03 00:00:00,954.754078,0.323284,1.245865e+05,42.185564,NaN,0.0000
2021-05-04 00:00:00,447.255692,0.130022,3.665589e+04,10.656232,NaN,0.0000
...,...,...,...,...,...,...
2024-01-02 00:05:54,62037.826588,26.350000,2.357720e+06,1001.420000,6.202542e+08,263447.3000
2024-01-03 00:05:23,63340.971988,26.849950,9.104339e+06,3859.288000,6.332830e+08,268445.8001
2024-01-04 00:05:47,59280.352474,26.900000,3.992150e+06,1811.541600,5.926850e+08,268946.2000
2024-01-05 00:05:06,60798.779058,26.749000,1.026890e+06,451.790000,6.078662e+08,267436.5020
2024-01-06 00:05:21,59360.778864,26.150000,2.743485e+06,1208.577900,5.934891e+08,261447.7000

## /nfts/{asset_platform_id}/contract/{contract_address}/market_chart

In [14]:
nft_historical_data_by_contract = api.nft_historical_data(
    asset_platform_id='ethereum', 
    contract_address='0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d',
    days=7
)
nft_historical_data_by_contract

,floor_price_usd,floor_price_native,h24_volume_usd,h24_volume_native,market_cap_usd,market_cap_native
timestamp,,,,,,
2023-12-30 07:50:26,61529.289123,26.745564,3.893897e+05,169.25999,6.151698e+08,267402.143932
2023-12-30 07:55:15,61529.289123,26.745564,3.893897e+05,169.25999,6.151698e+08,267402.143932
2023-12-30 08:00:32,61529.289123,26.745564,3.893897e+05,169.25999,6.151698e+08,267402.143932
2023-12-30 08:05:15,61529.289123,26.745564,3.893897e+05,169.25999,6.151698e+08,267402.143932
2023-12-30 08:10:09,61336.967025,26.745564,3.881726e+05,169.25999,6.132470e+08,267402.143932
...,...,...,...,...,...,...
2024-01-06 07:25:10,58313.585901,26.282900,3.017151e+06,1359.87990,5.830192e+08,262776.434200
2024-01-06 07:30:12,58313.585901,26.282900,3.017151e+06,1359.87990,5.830192e+08,262776.434200
2024-01-06 07:35:10,58313.585901,26.282900,3.017151e+06,1359.87990,5.830192e+08,262776.434200
2024-01-06 07:40:19,58583.514402,26.266600,2.973894e+06,1333.37990,5.857180e+08,262613.466800
2024-01-06 07:45:13,58583.514402,26.266600,2.973894e+06,1333.37990,5.857180e+08,262613.466800

## /nfts/{id}/tickers

In [15]:
nft_tickers = api.nft_market_tickers(nft_id='bored-ape-yacht-club')
nft_tickers.head()

,floor_price_in_native_currency,h24_volume_in_native_currency,native_currency,native_currency_symbol,updated_at,nft_marketplace_id,name,image,nft_collection_url
0,27.25,0.00,ethereum,ETH,2024-01-06T07:35:51.819Z,opensea,OpenSea,https://assets.coingecko.com/nft_marketplaces/...,https://opensea.io/collection/boredapeyachtclub
1,33.00,0.00,ethereum,ETH,2024-01-06T07:35:51.936Z,x2y2,X2Y2,https://assets.coingecko.com/nft_marketplaces/...,https://x2y2.io/collection/0xbc4ca0eda7647a8ab...
2,33.00,0.00,ethereum,ETH,2024-01-06T07:35:52.066Z,looksrare,LooksRare,https://assets.coingecko.com/nft_marketplaces/...,https://looksrare.org/collections/0xbc4ca0eda7...
3,26.27,1333.38,ethereum,ETH,2024-01-06T07:35:51.707Z,blur,Blur,https://assets.coingecko.com/nft_marketplaces/...,https://blur.io/collection/boredapeyachtclub

In [16]:
api.end_session()

'Session closed successfully.'